### PR TITLE
Add multi routing engine support for the "environment" module

### PR DESCRIPTION
**Pull request by AKYD**
(This will close: https://github.com/czerwonk/junos_exporter/issues/66)

Add tests
Extract PEM statistics

**! I do not have access to a satellite setup so the satellite test is not tested (not sure I understand what it does).**

### CODE REVIEW

**Review by czerwonk — APPROVED** [review]
LGTM

**Review by czerwonk — APPROVED** [review]
LGTM, Thanks! 👍

**Comment by AKYD** [comment]
@czerwonk did you by any chance test the satellite behavior, or just eyeballed the code?

I'm referring to :
https://github.com/czerwonk/junos_exporter/pull/135/files#diff-ef524dc00c4aca60ce490b02fb8e134018de8ab652ca69b61f2994edd7db41a3R103

**Comment by 4xoc** [comment]
> @czerwonk did you by any chance test the satellite behavior, or just eyeballed the code?
> 
> I'm referring to :
> https://github.com/czerwonk/junos_exporter/pull/135/files#diff-ef524dc00c4aca60ce490b02fb8e134018de8ab652ca69b61f2994edd7db41a3R103

Using satellite panics the exporter. I've created #139 that fixes this small typo.

**Pull request merged**
