### PR TITLE
update README.md to reflect all config options as per config.go

### PR DESCRIPTION
**Pull request by momorientes**

### CODE REVIEW

**Comment by ThomDietrich** [comment]
Hey @momorientes,
good call but why are all of them true? I suspect that the original author wanted to set the incentive to disable those not needed and I would agree, let's lead with example and be considerate of the amount of data pulled.

**Comment by momorientes** [comment]
@ThomDietrich fine by me, I would however argue, that the file should reflect the default behavior of the exporter if the file were absent. Is there any documentation on which features are enabled by default? I'm sadly not to versed in the code itself so I would appreciate a pointer.

**Comment by ThomDietrich** [comment]
Me neither. I'm also just barely a user :) Documentation wise I think the README could benefit from a list of all options, plus default, plus a description of what to expect. I had honestly a hard time deciding which data points are useful. I had to enable all and check the resulting tables for insights a few days later (of course I never did that and am generating unnecessary chatter and storage usage...)

Maybe something to consider - however I do not want to hijack your PR! @czerwonk wdyt?

**Comment by czerwonk** [comment]
Hey,
i think this PR gives a broad overview of the many modules we support now. So I would suggest to merge it as an improvement and to generate an overview table of all modules with the defaults (and possibly performance impact) in the next few weeks for the next release.

**Review by czerwonk — APPROVED** [review]
LGTM

**Pull request merged**
